language: node_js
node_js:
  - "4"
  - "10"
compiler: clang
env:
  - CXX=clang NODE_ENV=test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - clang
      - g++-4.8
